=== zimbabue1234/Validaci-n-de-documentos-XML-mediante-DTDs/curriculum.dtd
<!ELEMENT curriculum (informacion, estudios, habilidades, idiomas)>
<!ATTLIST curriculum lang (es) #REQUIRED>
<!ELEMENT informacion (nombre, apellidos, fechanacimiento, telefono, direccion, correo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechanacimiento (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT estudios (estudio+)>
<!ELEMENT estudio (nombre_estudio, anosdeformacion)>
<!ELEMENT nombre_estudio (#PCDATA)>
<!ELEMENT anosdeformacion (#PCDATA)>
<!ELEMENT habilidades (habilidad+)>
<!ELEMENT habilidad (#PCDATA)>
<!ELEMENT idiomas (idioma+)>
<!ELEMENT idioma  (nombre_idioma, titulo_idioma)>
<!ELEMENT nombre_idioma (#PCDATA)>
<!ELEMENT titulo_idioma (#PCDATA)>

=== zimbabue1234/Validaci-n-de-documentos-XML-mediante-DTDs/curriculum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "curriculum.dtd">

<curriculum lang="es">

    <informacion>
       <nombre>Muhammad</nombre>
       <apellidos>Amrabat Sumbul</apellidos>
       <fechanacimiento>12/12/1901</fechanacimiento>
       <telefono>878965654</telefono>
       <direccion>بارلخثضلح</direccion>
       <correo>muhammadamrabatsumbul@hotmail.com</correo>
    </informacion>
    
    <estudios>
        <estudio>
            <nombre_estudio>Dietetica</nombre_estudio>
            <anosdeformacion>4</anosdeformacion>
        </estudio>
    </estudios>

    <habilidades>
        <habilidad>Comunicación</habilidad>
        <habilidad>Bum BUM tam tam</habilidad>
        <habilidad>nose</habilidad>
    </habilidades>
    <idiomas>
        <idioma>
            <nombre_idioma>Árabe</nombre_idioma>
            <titulo_idioma>Nativo</titulo_idioma>
        </idioma>
        <idioma>
            <nombre_idioma>Colombiano marihuano</nombre_idioma>
            <titulo_idioma>C1</titulo_idioma>
        </idioma>
    </idiomas>
</curriculum>
