=== zimbabue1234/Validaci-n-de-documentos-XML-mediante-DTDs/ejercicio7.dtd
<!ELEMENT facturas (factura+)>
<!ATTLIST factura numero CDATA #REQUIRED>

<!ELEMENT factura (membrete, fecha, cliente, productos, resumen)>

<!ELEMENT membrete (razon_social_empresa, direccion_empresa, codigo_postal_empresa, poblacion_empresa, telefono_empresa, email_empresa)>
<!ATTLIST membrete cif ID #REQUIRED>

<!ELEMENT cif_empresa (#PCDATA)>
<!ELEMENT razon_social_empresa (#PCDATA)>
<!ELEMENT direccion_empresa (#PCDATA)>
<!ELEMENT codigo_postal_empresa (#PCDATA)>
<!ELEMENT poblacion_empresa (#PCDATA)>
<!ELEMENT telefono_empresa (#PCDATA)>
<!ELEMENT email_empresa (#PCDATA)>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT cliente (dni_cliente, nombre_cliente, direccion_cliente, codigo_postal_cliente, poblacion_cliente)>

<!ELEMENT dni_cliente (#PCDATA)>
<!ELEMENT nombre_cliente (#PCDATA)>
<!ELEMENT direccion_cliente (#PCDATA)>
<!ELEMENT codigo_postal_cliente (#PCDATA)>
<!ELEMENT poblacion_cliente (#PCDATA)>

<!ELEMENT productos (producto+)>

<!ELEMENT producto (cantidad_producto, descripcion_producto, precio_unitario, IVA)>
<!ATTLIST producto codigo ID #REQUIRED>

<!ELEMENT codigo_producto (#PCDATA)>
<!ELEMENT cantidad_producto (#PCDATA)>
<!ELEMENT descripcion_producto (#PCDATA)>
<!ELEMENT precio_unitario (#PCDATA)>
<!ELEMENT IVA (#PCDATA)>

<!ELEMENT resumen (forma_pago)>

<!ELEMENT forma_pago (#PCDATA)>
<!ATTLIST forma_pago tipo CDATA #REQUIRED>

=== zimbabue1234/Validaci-n-de-documentos-XML-mediante-DTDs/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "ejercicio7.dtd">

<facturas>
<factura numero="A006">
    <membrete cif="A23874">
        <razon_social_empresa>No comen jamón S.L</razon_social_empresa>
        <direccion_empresa>Av. Miquel Serra</direccion_empresa>
        <codigo_postal_empresa>928374</codigo_postal_empresa>
        <poblacion_empresa>Pedreguer</poblacion_empresa>
        <telefono_empresa>912 123 245</telefono_empresa>
        <email_empresa>miquelserra@miquelserra.com</email_empresa>
    </membrete>

    <fecha>18-11-2024</fecha>

    <cliente>
        <dni_cliente>723648924J</dni_cliente>
        <nombre_cliente>Serra Miquel</nombre_cliente>
        <direccion_cliente>Carrer Miquel Serra</direccion_cliente>
        <codigo_postal_cliente>928374</codigo_postal_cliente>
        <poblacion_cliente>Pedreguer</poblacion_cliente>
    </cliente>

    <productos>
        <producto codigo="LP001">
            <cantidad_producto>1</cantidad_producto>
            <descripcion_producto>Portátil Miquel Serra</descripcion_producto>
            <precio_unitario>800</precio_unitario>
            <IVA>21</IVA>
        </producto>

        <producto codigo="MQS23">
            <cantidad_producto>1</cantidad_producto>
            <descripcion_producto>Monitor de Miquel Serra</descripcion_producto>
            <precio_unitario>120</precio_unitario>
            <IVA>21</IVA>
        </producto>

        <producto codigo="SMQ281">
            <cantidad_producto>1</cantidad_producto>
            <descripcion_producto>Ratón de Miquel Serra</descripcion_producto>
            <precio_unitario>20</precio_unitario>
            <IVA>21</IVA>
        </producto>
    </productos>

    <resumen>
        <forma_pago tipo="Transferencia">Miquel Serra</forma_pago>
    </resumen>

    </factura>
</facturas>
